name: BUILD_AND_PUSH

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build docker image
      run:
        docker build -t ${GITHUB_REPOSITORY}:${GITHUB_REF:11} --build-arg DOCKER_VER=${GITHUB_REF:11} .
    - name: Upload Docker Image
      env:
        IMAGE_NAME: docker-container-pruner
      run:
        docker tag local-image docker.pkg.github.com/${GITHUB_REPOSITORY}/${IMAGE_NAME}:${GITHUB_REF:11}
        docker push docker.pkg.github.com/${GITHUB_REPOSITORY}/${IMAGE_NAME}:${GITHUB_REF:11}
